services:
  postgres:
    image: postgres:16.9
    restart: always
    environment:
      POSTGRES_USER: dev-user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dev_db
    ports:
      - 15432:5432
    expose:
      - "15432"
    volumes:
      - db-data:/var/lib/postgresql/data:cached

  # test-postgres:
  #   image: postgres:16.9
  #   restart: always
  #   environment:
  #     POSTGRES_USER: test-user
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: test_db
  #   ports:
  #     - 15434:5432 # Use a different port to avoid conflicts with the main database
  #   expose:
  #     - "15434" # Exposing the different port for clarity
  #   volumes:
  #     - test-db-data:/var/lib/postgresql/data:cached

  # backend:
  #   build:
  #     context: backend
  #     dockerfile: Dockerfile
  #   command: uv run /app/main.py
  #   # command: tail -f /app/main.py
  #   # command: uv run fastapi app/main.py --host 0.0.0.0 --port 8000
  #   tty: true
  #   # volumes:
  #   #   - ./backend:/app:cached
  #   #   - ./.docker/.ipython:/root/.ipython:cached
  #   environment:
  #     PYTHONPATH: .
  #     DATABASE_URL: "postgresql+asyncpg://dev-user:password@postgres:15432/dev_db"
  #   depends_on:
  #     - "postgres"
  #   ports:
  #     - 18000:8000
  #   develop:
  #     watch:
  #       - path: ./backend
  #         action: rebuild

  # frontend:
  #   build:
  #     context: frontend
  #     dockerfile: Dockerfile
  #   stdin_open: true
  #   volumes:
  #     - "./frontend:/app:cached"
  #     - "./frontend/node_modules:/app/node_modules:cached"
  #   environment:
  #     - NODE_ENV=development
  #   ports:
  #     - 3000:3000

volumes:
  db-data:
  test-db-data:
