version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ftracker
      POSTGRES_USER: ftracker_user
      POSTGRES_PASSWORD: secret
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pg_data:
